version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distance_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./distance_server/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./distance_server
    container_name: backend-api
    restart: always
    env_file:
      - ./distance_server/.env
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./distance_client
    container_name: frontend-app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: